services:
  - type: web
    name: dashboard-financiero
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
   startCommand: "streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0"
